### ISSUE TITLE
sometimes name is not loaded

### ISSUE THREAD

**Issue by jejewittt** [CMPUT301W18T23/GeoTask#56]
when viewing a tasks, hitting the star button and then hitting the bid button, i get this exception:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.geotask.myapplication.DataClasses.Task.getName()' on a null object reference
                      at com.geotask.myapplication.ViewTaskActivity.updateDisplayedValues(ViewTaskActivity.java:310)
                      at com.geotask.myapplication.ViewTaskActivity.updateStatus(ViewTaskActivity.java:627)
                      at com.geotask.myapplication.ViewTaskActivity.access$000(ViewTaskActivity.java:45)
                      at com.geotask.myapplication.ViewTaskActivity$1.onClick(ViewTaskActivity.java:255)

**Comment by jejewittt** [comment]
- this happens when clicking on viewBids - and nothing todo with the star/wishlist button
